# Generated by Django 6.0.2 on 2026-03-01 21:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=5)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timezone', models.CharField(blank=True, max_length=50)),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'cities',
                'ordering': ['-is_favorite', 'name'],
                'unique_together': {('name', 'country_code')},
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('found_result', models.BooleanField(default=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='weather.city')),
            ],
            options={
                'verbose_name_plural': 'search histories',
                'ordering': ['-searched_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField()),
                ('temp_min', models.FloatField()),
                ('temp_max', models.FloatField()),
                ('humidity', models.IntegerField()),
                ('wind_speed', models.FloatField()),
                ('description', models.CharField(max_length=200)),
                ('icon_code', models.CharField(max_length=10)),
                ('pop', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_forecasts', to='weather.city')),
            ],
            options={
                'ordering': ['forecast_date'],
                'unique_together': {('city', 'forecast_date')},
            },
        ),
        migrations.CreateModel(
            name='HourlyForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_time', models.DateTimeField()),
                ('temperature', models.FloatField()),
                ('feels_like', models.FloatField()),
                ('humidity', models.IntegerField()),
                ('wind_speed', models.FloatField()),
                ('description', models.CharField(max_length=200)),
                ('icon_code', models.CharField(max_length=10)),
                ('pop', models.FloatField(default=0, help_text='Probability of precipitation (0-1)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_forecasts', to='weather.city')),
            ],
            options={
                'ordering': ['forecast_time'],
                'unique_together': {('city', 'forecast_time')},
            },
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('temperature', models.FloatField(help_text='Temperature in Celsius')),
                ('feels_like', models.FloatField(help_text='Feels like temperature in Celsius')),
                ('temp_min', models.FloatField(help_text='Min temperature in Celsius')),
                ('temp_max', models.FloatField(help_text='Max temperature in Celsius')),
                ('condition', models.CharField(choices=[('clear', 'Clear'), ('clouds', 'Cloudy'), ('rain', 'Rain'), ('drizzle', 'Drizzle'), ('thunderstorm', 'Thunderstorm'), ('snow', 'Snow'), ('mist', 'Mist'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('icon_code', models.CharField(max_length=10)),
                ('humidity', models.IntegerField(help_text='Humidity percentage')),
                ('pressure', models.IntegerField(help_text='Pressure in hPa')),
                ('visibility', models.IntegerField(blank=True, help_text='Visibility in meters', null=True)),
                ('uv_index', models.FloatField(blank=True, null=True)),
                ('wind_speed', models.FloatField(help_text='Wind speed in m/s')),
                ('wind_direction', models.IntegerField(help_text='Wind direction in degrees')),
                ('wind_gust', models.FloatField(blank=True, null=True)),
                ('cloud_coverage', models.IntegerField(help_text='Cloud coverage percentage')),
                ('sunrise', models.DateTimeField(blank=True, null=True)),
                ('sunset', models.DateTimeField(blank=True, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_records', to='weather.city')),
            ],
            options={
                'ordering': ['-fetched_at'],
                'indexes': [models.Index(fields=['city', '-fetched_at'], name='weather_wea_city_id_c6fd4f_idx')],
            },
        ),
    ]
